[package]
name = "raknet-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raknet = { path = "../../" }
tokio = {version = "1.24.2", features = ["full"]}
